  
### Servidor
GET http://localhost:3000/

### Get Tasks
GET http://localhost:3000/tasks

### Get a Task by ID
GET http://localhost:3000/tasks/1

### Create a task
POST http://localhost:3000/tasks
Content-Type: application/json

{
    "title": "Primera Tarea",
    "detail": "Test1"
}

### Update Task
PUT http://localhost:3000/tasks/1
Content-Type: application/json

{
    "title": "Tarea Actualizada",
    "detail": "Test1Act"
}

### Delete Task
DELETE http://localhost:3000/tasks/1

### Status change to Completed
PUT http://localhost:3000/tasks/1?status=COMPLETED

### Status change to pending
PUT http://localhost:3000/tasks/1?status=PENDING